### ISSUE TITLE
Trim video crash

### ISSUE THREAD

**Issue by heberjeur** [you-apps/RecordYou#201]
### Steps to reproduce

Hello, the application crashes when I try to cut the audio
You can see that here :
https://drive.google.com/file/d/1Ktb7sBIIhrIrLyjvN5B8wqIiD8gnRA9k/view?usp=sharing

### Expected behavior

Ideally, the application should perform the cutting, display a success message, and allow me to open the file containing the data

### Actual behavior

The application has stopped.

### Record You version

7.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
- Could you please tell us what recording settings  you use?
- Does the app crash when trimming screen recordings?

**Comment by badlydrawnface** [comment]
Same problem, here is an attempt of trying to get some sort of traceback for the crash. May or may not be helpful. I reproduced this error by trying to play a trimmed file that failed due to crashing.

```
10-07 14:01:36.518  1153  1153 D MtpDeviceJNI: register_android_mtp_MtpDevice
10-07 14:01:36.585  1153  1153 E MediaPlayerNative: Unable to create media player
10-07 14:01:36.586  1153  1153 W MediaPlayer: Ignoring IO error while setting data source
10-07 14:01:36.586  1153  1153 W MediaPlayer: java.io.IOException: setDataSourceFD failed.: status=0x80000000
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.media.MediaPlayer._setDataSource(Native Method)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1272)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1253)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at r3.w0.C(SourceFile:82)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at r3.i0.C(SourceFile:24)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at q3.j$a.C(SourceFile:9)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at androidx.compose.foundation.h$b.n(SourceFile:13)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at o.g1$a.j(SourceFile:134)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at n6.a.t(Unknown Source:8)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at c2.a.d(Unknown Source:77)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at c7.i.p(SourceFile:129)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at c7.i.B(SourceFile:44)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at c7.i.t(SourceFile:17)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.t0.j1(SourceFile:51)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.t0.G0(Unknown Source:30)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at androidx.compose.foundation.a.G0(SourceFile:7)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:174)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.h.b(SourceFile:40)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at e1.g0.a(SourceFile:164)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at androidx.compose.ui.platform.AndroidComposeView.P(SourceFile:79)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at androidx.compose.ui.platform.AndroidComposeView.E(SourceFile:224)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:88)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4307)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.View.dispatchPointerEvent(View.java:15309)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6774)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6574)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6030)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6218)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6275)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9202)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9153)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9122)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9325)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.os.MessageQueue.next(MessageQueue.java:335)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.os.Looper.loopOnce(Looper.java:161)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.os.Looper.loop(Looper.java:288)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at android.app.ActivityThread.main(ActivityThread.java:7940)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at java.lang.reflect.Method.invoke(Native Method)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-07 14:01:36.586  1153  1153 W MediaPlayer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
10-07 14:01:36.587  1153  1153 E MediaPlayerNative: prepareAsync called in state 1, mPlayer(0x0)
--------- beginning of crash
10-07 14:01:36.593  1153  1153 E AndroidRuntime: FATAL EXCEPTION: main
10-07 14:01:36.593  1153  1153 E AndroidRuntime: Process: com.bnyro.recorder, PID: 1153
10-07 14:01:36.593  1153  1153 E AndroidRuntime: java.lang.IllegalStateException
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.media.MediaPlayer._prepare(Native Method)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.media.MediaPlayer.prepare(MediaPlayer.java:1309)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at r3.w0.C(SourceFile:99)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at r3.i0.C(SourceFile:24)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at q3.j$a.C(SourceFile:9)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at androidx.compose.foundation.h$b.n(SourceFile:13)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at o.g1$a.j(SourceFile:134)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at n6.a.t(Unknown Source:8)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at c2.a.d(Unknown Source:77)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at c7.i.p(SourceFile:129)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at c7.i.B(SourceFile:44)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at c7.i.t(SourceFile:17)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.t0.j1(SourceFile:51)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.t0.G0(Unknown Source:30)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at androidx.compose.foundation.a.G0(SourceFile:7)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:174)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.m.f(SourceFile:153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.h.b(SourceFile:40)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at e1.g0.a(SourceFile:164)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.P(SourceFile:79)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.E(SourceFile:224)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:88)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4307)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:15309)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6774)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6574)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6030)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6218)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6275)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9202)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9153)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9122)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9325)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:335)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:161)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7940)
10-07 14:01:36.593  1153  1153 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-07 14:01:36.594  1153  1153 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-07 14:01:36.594  1153  1153 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
10-07 14:01:36.594  1153  1153 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-07 14:01:36.594  1153  1153 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
10-07 14:01:36.594  1153  1153 E AndroidRuntime: 	Suppressed: c7.k0: [androidx.compose.ui.platform.p2@1fea406, e0.g@209dac7, u1{Cancelling}@bc4f8f4, i1@770881d]
```

**Comment by SuhasDissa** [comment]
Logs produced by release builds of the app are not very useful. If you are interested in helping us, please use a debug build to get the logs. You can grab one from [here](https://github.com/you-apps/RecordYou/actions)

**Comment by SuhasDissa** [comment]
> The only setting I modified was the directory the application used.

Yes, this is the cause of the app crash.

We'll fix that bug soon. Thank you for your help.
