### ISSUE TITLE
When I updated to version 3.0, the app closes when I press "record video".

### ISSUE THREAD

**Issue by Wjxfi** [you-apps/RecordYou#25]
FATAL EXCEPTION: main
Process: com.bnyro.recorder, PID: 7148
java.lang.IllegalStateException
	at android.media.MediaRecorder.start(Native Method)
	at c3.f$a.onServiceConnected(SourceFile:274)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2096)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2129)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by Bnyro** [comment]
I can't reproduce the issue.

**Comment by Bnyro** [comment]
That's interesting, which are your screen's height and width?

**Comment by Bnyro** [comment]
I've tested five different devices now and still can't reproduce it.
The reason is probably related to the width and height of the recording and device, but I can't figure out what exactly the issue is without being able to reproduce it on one of my devices or an emulator.

**Comment by Bnyro** [comment]
Fair, the Resizable A13 emulator is able to reproduce it.

**Comment by shuvashish76** [comment]
Logs:

```
FATAL EXCEPTION: main
Process: com.bnyro.recorder, PID: 31253
java.lang.IllegalStateException
	at android.media.MediaRecorder.start(Native Method)
	at com.bnyro.recorder.services.ScreenRecorderService.g(SourceFile:352)
	at k3.e$a.onServiceConnected(SourceFile:96)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2096)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2129)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

Similar crash happened to me when starting screen recording.
App version: **5.3 (13)**
Android release version: 12
Android SDK version: 31
Device brand: motorola
Device model: moto g71 5G

Screen Details
Density: xhdpi (356 DPI)
Scaling factor: 2.2250001
Size: 1080px × 2400px
Window size: 1080px × 2193px
Refresh rate: 60.0 Hz

Additional details:

Not sure if it's the same crash. Hide this comment if it's a different one, I'll create another issue. Thanks.

**Comment by linsui** [comment]
I still get this error on 5.3.

```
FATAL EXCEPTION: main
Process: com.bnyro.recorder, PID: 11734
java.lang.NullPointerException
	at o3.f.b(SourceFile:148)
	at com.bnyro.recorder.services.ScreenRecorderService.g(SourceFile:304)
	at k3.e$a.onServiceConnected(SourceFile:96)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2188)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2221)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by SuhasDissa** [comment]
Closed due to inactivity
